### ISSUE TITLE
App getting close on connection (without error log)

### ISSUE THREAD

**Issue by shashankjamdade** [nhancv/nc-kurento-android#4]
I have set the nodejs backend at my local machine and run the test android app with given code by putting my localIp address (common n/w ip). Its working fine as if I tried to call unregistered user it shows the toast for user unregister etc. when I tried with register user and tried to connect them android app get close automatically without showing log in android studio. I am unable to figure out the problem, please help me.

**Comment by zhouyongxyz** [comment]
When I use https://github.com/Kurento/kurento-tutorial-java.git as server, error echoed as the title.something wrong when websocket try shakhand.

01-29 17:39:41.319 4029-4603/com.nhancv.kurentoandroid W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:219)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.waitForHandshake(ConscryptFileDescriptorSocket.java:468)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.getInputStream(ConscryptFileDescriptorSocket.java:431)
        at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:211)
        at java.lang.Thread.run(Thread.java:764)
01-29 17:39:41.320 4029-4603/com.nhancv.kurentoandroid W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:661)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:539)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
